### ISSUE TITLE
New Endpoint "/random"

### ISSUE THREAD

**Issue by dakshsethi** [GDSC-RTU/quotes-api#21]
Hi,
I want to work on creating a new endpoint for this Quotes Repo.
The endpoint is `/random`, whenever a `GET` request is being sent to this endpoint, it will send select one random quote from the array and then send it back.

@ishubham21 assign this to me.
Thanks

**Comment by ishubham21** [comment]
> Hi, I want to work on creating a new endpoint for this Quotes Repo. The endpoint is `/random`, whenever a `GET` request is being sent to this endpoint, it will send select one random quote from the array and then send it back.
> 
> @ishubham21 assign this to me. Thanks

Assigned to you @dakshsethi
